packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  next: ^16.1.1
  "@libsql/client": 0.15.15
  libsql: 0.5.22
  "@trpc/server": ^11.7.2
  "@trpc/client": ^11.7.2
  better-auth: ^1.4.18
  drizzle-orm: ^0.45.1
